language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console --fix-missing
 
script:
  - xbuild CI.proj
  - nunit-console ./src/FluentMigrator.Tests/bin/Debug/FluentMigrator.Tests.dll -exclude Integration,NotWorkingOnMono
