language: c
sudo: false
addons:
  apt:
    packages:
      - mono-devel
      - mono-gmcs
      - nunit-console
script:
  - xbuild CI.proj
  - nunit-console ./src/Gemini.Tests/bin/Debug/Gemini.Tests.dll -exclude Integration,NotWorkingOnMono
