language: c
sudo: false
addons:
  apt:
    packages:
      - mono-devel
      - mono-gmcs
      - nunit-console
script:
  - xbuild ./src/Gemini.csproj
  - nunit-console ./src/bin/Debug/Gemini.exe -exclude Integration,NotWorkingOnMono
