version: 0.0.{build}
branches:
  only:
    - master
skip_commits:
  message: /(Create|Add).*\.(png|jpg|jpeg|bmp|gif|md)/
#init:
#- git config --global core.autocrlf input
skip_tags: true
os: Visual Studio 2015
configuration: release
platform: x86
clone_depth: 5
environment:
  access_token:
    secure: vYKH/rSJ9uglA2VeIJlyTr9G8aOxg2j0UC/DVmA0iUFw1JQpRBIwWxbRfvKfJlPt
assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}.{build}'
  assembly_informational_version: '{version}-rc1'
before_build:
  - ps: nuget restore
  - ps: copy-item -path packages -destination src -recurse
after_build:
  - cd src\bin\release\
  - 7z a Gemini.zip Gemini.exe
  - cd ..\..\..
  - ps: copy-item src\bin\release\Gemini.zip .
  - ps: copy-item src\bin\release\Gemini.exe .
  - echo %APPVEYOR_BUILD_VERSION% >> "VersionInfo.dat"
artifacts:
  - path: Gemini.zip
deploy:
  - provider: GitHub
    artifact: /Gemini\.exe|Gemini\.zip|VersionInfo\.dat/
    draft: false
    auth_token: vYKH/rSJ9uglA2VeIJlyTr9G8aOxg2j0UC/DVmA0iUFw1JQpRBIwWxbRfvKfJlPt
    prerelease: false
on_success:
  - git config credential.helper store
  - echo "https://%access_token%:x-oauth-basic@github.com" > "%userprofile%\.git-credential"
  - git add Gemini.zip
  - git add Gemini.exe
  - git add VersionInfo.dat
  - git commit -m "Add latest build from AppVeyor\n[skip ci]"
  - git push --verbose origin %appveyor_repo_branch%
