version: 0.0.3.1
branches:
  only:
    - master
skip_commits:
  message: /(Create|Add).*\.(png|jpg|jpeg|bmp|gif|md)/
#init:
#- git config --global core.autocrlf input
skip_tags: true
os: Visual Studio 2015
configuration: release
platform: x86
clone_depth: 5
environment:
  access_token:
    secure: kFaS3hFnbZuEAGLC9L5zYcom8fYp6vYmLTjoMJtvP5vffxrHSIZAT1ADp7BWxO7ii7lY0WhuX3+oN592hZbW5q823Jv3wU8ErCZFxAjAmWA=
build_script:
- ps: nuget restore
- ps: move-item -path packages -destination src
- msbuild "Gemini.sln" /verbosity:minimal /logger:"%programfiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd src\bin\release\
- 7z a Gemini.zip Gemini.exe
- cd ..\..\..
- ps: move-item src\bin\release\Gemini.zip .
- ps: move-item src\bin\release\Gemini.exe .
artifacts:
- path: Gemini.zip
  name: Gemini
before_deploy:
- echo %APPVEYOR_BUILD_VERSION% >> "VersionInfo.dat"
deploy:
- provider: GitHub
  tag: b-$(APPVEYOR_REPO_TAG_NAME)
  release: Gemini v$(APPVEYOR_REPO_TAG_NAME)
  description: Automatic build from Appveyor.
  auth_token:
    secure: kFaS3hFnbZuEAGLC9L5zYcom8fYp6vYmLTjoMJtvP5vffxrHSIZAT1ADp7BWxO7ii7lY0WhuX3+oN592hZbW5q823Jv3wU8ErCZFxAjAmWA=
  artifact: Gemini.zip
  draft: false
  prerelease: true
on_success:
  - git config credential.helper store
  - echo "https://%access_token%:x-oauth-basic@github.com" > "%userprofile%\.git-credential"
  - git add Gemini.zip
  - git add Gemini.exe
  - git add VersionInfo.dat
  - git commit -m "Add latest build from AppVeyor\n[skip ci]"
  - git push --verbose origin %appveyor_repo_branch%
