version: 0.0.3.{build}
branches:
  only:
    - master
skip_commits:
  message: /(Create|Add).*\.(png|jpg|jpeg|bmp|gif|md)/
#init:
#- git config --global core.autocrlf input
skip_tags: true
os: Visual Studio 2015
configuration: release
platform: x86
clone_depth: 5
environment:
  access_token:
    secure: kFaS3hFnbZuEAGLC9L5zYcom8fYp6vYmLTjoMJtvP5vffxrHSIZAT1ADp7BWxO7ii7lY0WhuX3+oN592hZbW5q823Jv3wU8ErCZFxAjAmWA=
build_script:
- ps: nuget restore
- ps: copy-item -path packages -destination src -recurse
- msbuild "Gemini.sln" /verbosity:minimal /logger:"%programfiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd src\bin\release\
- 7z a Gemini.zip Gemini.exe
- cd ..\..\..
- ps: copy-item src\bin\release\Gemini.zip .
- ps: copy-item src\bin\release\Gemini.exe .
artifacts:
- path: Gemini.zip
  name: Gemini
before_deploy:
- echo %APPVEYOR_BUILD_VERSION% >> "VersionInfo.dat"
deploy:
- provider: GitHub
  release: Gemini v$(APPVEYOR_BUILD_VERSION)
  description: Automatic build from Appveyor.[skip ci]
  auth_token:
    secure: kFaS3hFnbZuEAGLC9L5zYcom8fYp6vYmLTjoMJtvP5vffxrHSIZAT1ADp7BWxO7ii7lY0WhuX3+oN592hZbW5q823Jv3wU8ErCZFxAjAmWA=
  draft: false
  prerelease: true
